# Generated by Django 5.2.4 on 2025-07-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("university", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
                ("v_subject", models.CharField(max_length=255)),
                ("v_title", models.CharField(max_length=255)),
                ("v_unit", models.CharField(max_length=255)),
                ("v_subtopic", models.CharField(max_length=255)),
                ("v_description", models.CharField(max_length=255)),
                ("video_data", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("principal", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("pincode", models.CharField(max_length=255)),
                ("affiliation", models.CharField(max_length=255)),
                ("website", models.CharField(max_length=255)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                ("status", models.CharField(max_length=255)),
                ("payment", models.CharField(max_length=255)),
                ("branches", models.ManyToManyField(to="app.branch")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("year", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                (
                    "branches",
                    models.ManyToManyField(related_name="subjects", to="app.branch"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("PRN", models.CharField(max_length=255, unique=True)),
                ("mobile", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("year", models.CharField(max_length=255)),
                ("division", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("password", models.CharField(max_length=128)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                ("branch", models.ManyToManyField(blank=True, to="app.branch")),
                ("subject", models.ManyToManyField(blank=True, to="app.subject")),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=255)),
                ("qualification", models.CharField(max_length=255)),
                ("experience", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("password", models.CharField(max_length=128)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                ("post", models.CharField(blank=True, max_length=255)),
                ("division", models.CharField(blank=True, max_length=255)),
                ("branch", models.ManyToManyField(blank=True, to="app.branch")),
                ("subject", models.ManyToManyField(blank=True, to="app.subject")),
            ],
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("year", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=255)),
                ("c_code", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=255)),
                ("subpoint", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("file", models.FileField(upload_to="")),
                ("branch_id", models.CharField(max_length=255)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.teacher"
                    ),
                ),
            ],
        ),
    ]
